version: "3.9"

services:
  abs-autoconverter:
    build: .
    container_name: abs-autoconverter
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - absnet
    # Optional: if you want logs persisted
    # volumes:
    #   - ./logs:/app/logs

networks:
  absnet:
    external: false
